# Generated by Django 5.1.2 on 2024-10-25 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_cart_added_at_alter_cart_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
