# Generated by Django 5.1.2 on 2024-10-25 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_product'),
        ('shop', '0004_delete_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
